/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.domicilios.presentation.vista;

import co.unicauca.domicilios.access.ClienteAccessImplSockets;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 * @author Luis Romero, Jose Nicolas Santander
 */
public class IniciarSesionCliente extends javax.swing.JFrame {
	
	/**
	 * Creates new form IniciarSesionCliente
	 */
	public IniciarSesionCliente() {
		initComponents();
		setLocationRelativeTo(null);
		initIcons();
		
		TextPrompt textCorreoElectronicoC = new TextPrompt("Correo Electronico", txtCorreoElectronicoCliente);
		TextPrompt textContrasenaC = new TextPrompt("Contrasena", txtContrasenaCliente);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		pnlIniciarSesionCliente = new javax.swing.JPanel();
		pnlContenedorInicioSesionCliente = new javax.swing.JPanel();
		txtCorreoElectronicoCliente = new javax.swing.JTextField();
		txtContrasenaCliente = new javax.swing.JPasswordField();
		btnIniciarSesionCliente = new javax.swing.JButton();
		btnRegistrarseCliente = new javax.swing.JButton();
		btnAtras = new javax.swing.JButton();
		lblUsuario = new javax.swing.JLabel();
		lblContrasena = new javax.swing.JLabel();
		btnRecuperarContrasena = new javax.swing.JButton();
		lblFotoInicio = new javax.swing.JLabel();
		sptCorreoCliente = new javax.swing.JSeparator();
		sptContrasenaCliente = new javax.swing.JSeparator();
		pnlInicioSesionCliente = new javax.swing.JPanel();
		lblFondoInicioSesionCliente = new javax.swing.JLabel();
		lblMinimizar = new javax.swing.JLabel();
		lblSalir = new javax.swing.JLabel();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Deliverya App");
		setBackground(new java.awt.Color(255, 255, 255));
		setUndecorated(true);
		
		pnlIniciarSesionCliente.setBackground(new java.awt.Color(255, 255, 255));
		
		pnlContenedorInicioSesionCliente.setBackground(new java.awt.Color(255, 255, 255));
		pnlContenedorInicioSesionCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		
		txtCorreoElectronicoCliente.setBorder(null);
		pnlContenedorInicioSesionCliente.add(txtCorreoElectronicoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 153, -1));
		
		txtContrasenaCliente.setBorder(null);
		pnlContenedorInicioSesionCliente.add(txtContrasenaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 153, -1));
		
		btnIniciarSesionCliente.setBorder(null);
		btnIniciarSesionCliente.setBorderPainted(false);
		btnIniciarSesionCliente.setContentAreaFilled(false);
		btnIniciarSesionCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnIniciarSesionCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnIniciarSesionClienteActionPerformed(evt);
			}
		});
		pnlContenedorInicioSesionCliente.add(btnIniciarSesionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 32, 32));
		
		btnRegistrarseCliente.setBackground(new java.awt.Color(255, 255, 255));
		btnRegistrarseCliente.setForeground(new java.awt.Color(51, 51, 255));
		btnRegistrarseCliente.setText("Registrarse");
		btnRegistrarseCliente.setBorder(null);
		btnRegistrarseCliente.setBorderPainted(false);
		btnRegistrarseCliente.setContentAreaFilled(false);
		btnRegistrarseCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnRegistrarseCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnRegistrarseClienteActionPerformed(evt);
			}
		});
		pnlContenedorInicioSesionCliente.add(btnRegistrarseCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
		
		btnAtras.setBorder(null);
		btnAtras.setBorderPainted(false);
		btnAtras.setContentAreaFilled(false);
		btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnAtras.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAtrasActionPerformed(evt);
			}
		});
		pnlContenedorInicioSesionCliente.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 32, 32));
		pnlContenedorInicioSesionCliente.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 24, 24));
		pnlContenedorInicioSesionCliente.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 24, 24));
		
		btnRecuperarContrasena.setBackground(new java.awt.Color(255, 255, 255));
		btnRecuperarContrasena.setForeground(new java.awt.Color(55, 55, 255));
		btnRecuperarContrasena.setText("Recuperar contrase�a");
		btnRecuperarContrasena.setBorder(null);
		btnRecuperarContrasena.setBorderPainted(false);
		btnRecuperarContrasena.setContentAreaFilled(false);
		btnRecuperarContrasena.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		pnlContenedorInicioSesionCliente.add(btnRecuperarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));
		pnlContenedorInicioSesionCliente.add(lblFotoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 64, 64));
		pnlContenedorInicioSesionCliente.add(sptCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 150, -1));
		pnlContenedorInicioSesionCliente.add(sptContrasenaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 150, -1));
		
		pnlInicioSesionCliente.setBackground(new java.awt.Color(255, 255, 255));
		
		javax.swing.GroupLayout pnlInicioSesionClienteLayout = new javax.swing.GroupLayout(pnlInicioSesionCliente);
		pnlInicioSesionCliente.setLayout(pnlInicioSesionClienteLayout);
		pnlInicioSesionClienteLayout.setHorizontalGroup(
				pnlInicioSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(lblFondoInicioSesionCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
		);
		pnlInicioSesionClienteLayout.setVerticalGroup(
				pnlInicioSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(lblFondoInicioSesionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
		);
		
		lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblMinimizarMouseClicked(evt);
			}
		});
		
		lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblSalirMouseClicked(evt);
			}
		});
		
		javax.swing.GroupLayout pnlIniciarSesionClienteLayout = new javax.swing.GroupLayout(pnlIniciarSesionCliente);
		pnlIniciarSesionCliente.setLayout(pnlIniciarSesionClienteLayout);
		pnlIniciarSesionClienteLayout.setHorizontalGroup(
				pnlIniciarSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIniciarSesionClienteLayout.createSequentialGroup()
								.addGap(0, 815, Short.MAX_VALUE)
								.addComponent(lblMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(lblSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(pnlIniciarSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(pnlIniciarSesionClienteLayout.createSequentialGroup()
										.addComponent(pnlContenedorInicioSesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(pnlInicioSesionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(57, 57, 57)))
		);
		pnlIniciarSesionClienteLayout.setVerticalGroup(
				pnlIniciarSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlIniciarSesionClienteLayout.createSequentialGroup()
								.addContainerGap()
								.addGroup(pnlIniciarSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(lblMinimizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(lblSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(383, Short.MAX_VALUE))
						.addGroup(pnlIniciarSesionClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(pnlContenedorInicioSesionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
								.addComponent(pnlInicioSesionCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(pnlIniciarSesionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(pnlIniciarSesionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
	
	}//GEN-LAST:event_btnAtrasActionPerformed
	
	private void btnRegistrarseClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseClienteActionPerformed
		new RegistroCliente().setVisible(true);
		super.dispose();
	}//GEN-LAST:event_btnRegistrarseClienteActionPerformed
	
	private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
	
	}//GEN-LAST:event_lblMinimizarMouseClicked
	
	private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
		int dialogo = JOptionPane.YES_NO_OPTION;
		int aux = 0;
		int resultado = JOptionPane.showConfirmDialog(null, "¿Desea Salir?", "Deliverya App", dialogo, aux, new ImageIcon("src/main/java/co/unicauca/domicilios/presentation/imagenes/salida.png"));
		
		if (resultado == 0) {
			System.exit(0);
		}
	}//GEN-LAST:event_lblSalirMouseClicked
	
	private void btnIniciarSesionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionClienteActionPerformed
		if (txtCorreoElectronicoCliente.getText().isEmpty() || txtContrasenaCliente.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Ningun campo puede estar vacio");
		} else {
			try {
				ClienteAccessImplSockets sc = new ClienteAccessImplSockets();
				int dialogo = JOptionPane.CLOSED_OPTION;
				int aux = 0;
				String correo = txtCorreoElectronicoCliente.getText();
				if (sc.findCliente(correo) == null) {
					JOptionPane.showMessageDialog(null, "Correo Incorrecto... *para fines de este laboratorio solo se realiza la validacion de correo");
				} else {
					JOptionPane.showMessageDialog(null, "Encontrados...");
					
				}
			} catch (Exception e) {
				System.out.println(e.getMessage());
			}
		}
	}//GEN-LAST:event_btnIniciarSesionClienteActionPerformed
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(IniciarSesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(IniciarSesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(IniciarSesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(IniciarSesionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new IniciarSesionCliente().setVisible(true);
			}
		});
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAtras;
	private javax.swing.JButton btnIniciarSesionCliente;
	private javax.swing.JButton btnRecuperarContrasena;
	private javax.swing.JButton btnRegistrarseCliente;
	private javax.swing.JLabel lblContrasena;
	private javax.swing.JLabel lblFondoInicioSesionCliente;
	private javax.swing.JLabel lblFotoInicio;
	private javax.swing.JLabel lblMinimizar;
	private javax.swing.JLabel lblSalir;
	private javax.swing.JLabel lblUsuario;
	private javax.swing.JPanel pnlContenedorInicioSesionCliente;
	private javax.swing.JPanel pnlIniciarSesionCliente;
	private javax.swing.JPanel pnlInicioSesionCliente;
	private javax.swing.JSeparator sptContrasenaCliente;
	private javax.swing.JSeparator sptCorreoCliente;
	private javax.swing.JPasswordField txtContrasenaCliente;
	private javax.swing.JTextField txtCorreoElectronicoCliente;
	
	// End of variables declaration//GEN-END:variables
	private void initIcons() {
		addIcon(lblFondoInicioSesionCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/FondoInicioSesion.png");
		addIcon(btnAtras, "src/main/java/co/unicauca/domicilios/presentation/imagenes/atrasOff.png");
		addIconRollover(btnAtras, "src/main/java/co/unicauca/domicilios/presentation/imagenes/atrasOn.png");
		addIcon(lblUsuario, "src/main/java/co/unicauca/domicilios/presentation/imagenes/usuario.png");
		addIcon(lblContrasena, "src/main/java/co/unicauca/domicilios/presentation/imagenes/contrasena.png");
		addIcon(lblFotoInicio, "src/main/java/co/unicauca/domicilios/presentation/imagenes/login.png");
		addIcon(btnIniciarSesionCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/iniciar-sesionOff.png");
		addIconRollover(btnIniciarSesionCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/iniciar-sesionOn.png");
		addIcon(lblSalir, "src/main/java/co/unicauca/domicilios/presentation/imagenes/cancelar.png");
		addIcon(lblMinimizar, "src/main/java/co/unicauca/domicilios/presentation/imagenes/flecha-hacia-abajo.png");
	}
	
	private void addIcon(JLabel lb, String pathIcon) {
		ImageIcon img = new ImageIcon(pathIcon);
		Icon icono = new ImageIcon(img.getImage().getScaledInstance(
				lb.getWidth(),
				lb.getHeight(),
				Image.SCALE_DEFAULT));
		lb.setIcon(icono);
		this.repaint();
	}
	
	private void addIcon(JButton bt, String pathIcon) {
		ImageIcon img = new ImageIcon(pathIcon);
		Icon icono = new ImageIcon(img.getImage().getScaledInstance(
				bt.getWidth(),
				bt.getHeight(),
				Image.SCALE_DEFAULT));
		bt.setIcon(icono);
		this.repaint();
	}
	
	private void addIconRollover(JButton bt, String pathIcon) {
		ImageIcon img = new ImageIcon(pathIcon);
		Icon icono = new ImageIcon(img.getImage().getScaledInstance(
				bt.getWidth(),
				bt.getHeight(),
				Image.SCALE_DEFAULT));
		bt.setRolloverIcon(icono);
		this.repaint();
	}
}
