/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.domicilios.presentation.vista;

import co.unicauca.domicilios.domain.CreateNewClient;

import javax.swing.*;
import java.awt.*;

/**
 * @author Luis Romero, Jose Nicolas Santander
 */
public class RegistroCliente extends javax.swing.JFrame {
	
	/**
	 * Creates new form RegistroCliente
	 */
	public RegistroCliente() {
		initComponents();
		setLocationRelativeTo(null);
		initIcons();
		
		TextPrompt textNombreCompletoC = new TextPrompt("Nombre completo", txtRegistroNombreCompleto);
		TextPrompt textApellidoCompletoC = new TextPrompt("Apellido completo", txtRegistroApellidoCompleto);
		TextPrompt textFechaNacimientoC = new TextPrompt("DD/MM/AAAA", txtFechaNacimiento);
		TextPrompt textCorreoElectronicoC = new TextPrompt("Correo Electronico", txtRegistroCorreoCliente);
		TextPrompt textContrasenaC = new TextPrompt("ContraseÃ±a", txtRegistroContrasenaCliente);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		
		pnlRegistroCliente = new javax.swing.JPanel();
		pnlContenedorRegistroCliente = new javax.swing.JPanel();
		lblNombreCompleto = new javax.swing.JLabel();
		txtRegistroNombreCompleto = new javax.swing.JTextField();
		lblApellidoCompleto = new javax.swing.JLabel();
		txtRegistroApellidoCompleto = new javax.swing.JTextField();
		lblFechaNacimiento = new javax.swing.JLabel();
		txtFechaNacimiento = new javax.swing.JTextField();
		lblRegistroCorreoCliente = new javax.swing.JLabel();
		txtRegistroCorreoCliente = new javax.swing.JTextField();
		lblRegistroContrasenaCliente = new javax.swing.JLabel();
		txtRegistroContrasenaCliente = new javax.swing.JPasswordField();
		btnRegistrarCliente = new javax.swing.JButton();
		lblTerminos = new javax.swing.JLabel();
		btnTerminos = new javax.swing.JButton();
		lblLogoDecorado = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		jSeparator3 = new javax.swing.JSeparator();
		jSeparator4 = new javax.swing.JSeparator();
		jSeparator5 = new javax.swing.JSeparator();
		lblSalir = new javax.swing.JLabel();
		lblMinimizar = new javax.swing.JLabel();
		pnlFondoRegistroCliente = new javax.swing.JPanel();
		lblRegistroCliente = new javax.swing.JLabel();
		btnAtras = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Deliverya App");
		setBackground(new java.awt.Color(255, 255, 255));
		setUndecorated(true);
		
		pnlRegistroCliente.setBackground(new java.awt.Color(255, 255, 255));
		
		pnlContenedorRegistroCliente.setBackground(new java.awt.Color(255, 255, 255));
		pnlContenedorRegistroCliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		
		lblNombreCompleto.setBackground(new java.awt.Color(255, 255, 255));
		pnlContenedorRegistroCliente.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 24, 24));
		
		txtRegistroNombreCompleto.setBorder(null);
		pnlContenedorRegistroCliente.add(txtRegistroNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 141, -1));
		pnlContenedorRegistroCliente.add(lblApellidoCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 24, 24));
		
		txtRegistroApellidoCompleto.setBorder(null);
		pnlContenedorRegistroCliente.add(txtRegistroApellidoCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 141, -1));
		pnlContenedorRegistroCliente.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 24, 24));
		
		txtFechaNacimiento.setBorder(null);
		pnlContenedorRegistroCliente.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 141, -1));
		pnlContenedorRegistroCliente.add(lblRegistroCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 24, 24));
		
		txtRegistroCorreoCliente.setBorder(null);
		pnlContenedorRegistroCliente.add(txtRegistroCorreoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 141, -1));
		pnlContenedorRegistroCliente.add(lblRegistroContrasenaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 24, 24));
		
		txtRegistroContrasenaCliente.setBorder(null);
		pnlContenedorRegistroCliente.add(txtRegistroContrasenaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 141, -1));
		
		btnRegistrarCliente.setBorder(null);
		btnRegistrarCliente.setBorderPainted(false);
		btnRegistrarCliente.setContentAreaFilled(false);
		btnRegistrarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btnRegistrarClienteActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
		pnlContenedorRegistroCliente.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 32, 32));
		
		lblTerminos.setText("Al registrarse aceptas nuestros");
		pnlContenedorRegistroCliente.add(lblTerminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));
		
		btnTerminos.setBackground(new java.awt.Color(255, 255, 255));
		btnTerminos.setForeground(new java.awt.Color(55, 55, 255));
		btnTerminos.setText("Terminos y condiciones");
		btnTerminos.setBorder(null);
		btnTerminos.setBorderPainted(false);
		btnTerminos.setContentAreaFilled(false);
		btnTerminos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		pnlContenedorRegistroCliente.add(btnTerminos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));
		pnlContenedorRegistroCliente.add(lblLogoDecorado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 64, 64));
		pnlContenedorRegistroCliente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 140, -1));
		pnlContenedorRegistroCliente.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, -1));
		pnlContenedorRegistroCliente.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 140, -1));
		pnlContenedorRegistroCliente.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, -1));
		pnlContenedorRegistroCliente.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 140, -1));
		
		lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblSalirMouseClicked(evt);
			}
		});
		pnlContenedorRegistroCliente.add(lblSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 24, 24));
		
		lblMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		lblMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				lblMinimizarMouseClicked(evt);
			}
		});
		pnlContenedorRegistroCliente.add(lblMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 24, 24));
		
		pnlFondoRegistroCliente.setBackground(new java.awt.Color(255, 255, 255));
		
		lblRegistroCliente.setBackground(new java.awt.Color(255, 255, 255));
		
		btnAtras.setBorder(null);
		btnAtras.setBorderPainted(false);
		btnAtras.setContentAreaFilled(false);
		btnAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		btnAtras.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAtrasActionPerformed(evt);
			}
		});
		
		javax.swing.GroupLayout pnlFondoRegistroClienteLayout = new javax.swing.GroupLayout(pnlFondoRegistroCliente);
		pnlFondoRegistroCliente.setLayout(pnlFondoRegistroClienteLayout);
		pnlFondoRegistroClienteLayout.setHorizontalGroup(
				pnlFondoRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlFondoRegistroClienteLayout.createSequentialGroup()
								.addContainerGap()
								.addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(lblRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
		);
		pnlFondoRegistroClienteLayout.setVerticalGroup(
				pnlFondoRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlFondoRegistroClienteLayout.createSequentialGroup()
								.addComponent(lblRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 2, Short.MAX_VALUE))
						.addGroup(pnlFondoRegistroClienteLayout.createSequentialGroup()
								.addContainerGap()
								.addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);
		
		javax.swing.GroupLayout pnlRegistroClienteLayout = new javax.swing.GroupLayout(pnlRegistroCliente);
		pnlRegistroCliente.setLayout(pnlRegistroClienteLayout);
		pnlRegistroClienteLayout.setHorizontalGroup(
				pnlRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(pnlRegistroClienteLayout.createSequentialGroup()
								.addComponent(pnlFondoRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(pnlContenedorRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
		);
		pnlRegistroClienteLayout.setVerticalGroup(
				pnlRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(pnlFondoRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(pnlContenedorRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
		);
		
		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGap(0, 0, Short.MAX_VALUE)
								.addComponent(pnlRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(pnlRegistroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
		);
		
		pack();
	}// </editor-fold>//GEN-END:initComponents
	
	private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
	
	}//GEN-LAST:event_btnAtrasActionPerformed
	
	private void lblMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizarMouseClicked
	
	}//GEN-LAST:event_lblMinimizarMouseClicked
	
	private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
		int dialogo = JOptionPane.YES_NO_OPTION;
		int aux = 0;
		int resultado = JOptionPane.showConfirmDialog(null, "Â¿Desea Salir?", "Deliverya App", dialogo, aux, new ImageIcon("src/main/java/co/unicauca/domicilios/presentation/imagenes/salida.png"));
		
		if (resultado == 0) {
			System.exit(0);
		}
	}//GEN-LAST:event_lblSalirMouseClicked
	
	private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) throws Exception {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
		CreateNewClient createNewClient = new CreateNewClient();
		
		if (txtRegistroNombreCompleto.getText().isEmpty() || txtRegistroApellidoCompleto.getText().isEmpty() || txtFechaNacimiento.getText().isEmpty() ||
				txtRegistroCorreoCliente.getText().isEmpty() || txtRegistroContrasenaCliente.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Ningun campo puede estar vacio");
		} else {
			int dialogo = JOptionPane.CLOSED_OPTION;
			int aux = 0;
			String nombreCliente = txtRegistroNombreCompleto.getText();
			String apellidoCliente = txtRegistroApellidoCompleto.getText();
			String fechaNacCliente = txtFechaNacimiento.getText();
			String correoCliente = txtRegistroCorreoCliente.getText();
			String contrasenaCliente = txtRegistroContrasenaCliente.getText();
			createNewClient.clientRegistry(nombreCliente, apellidoCliente, fechaNacCliente, correoCliente, contrasenaCliente);
			int resultado = JOptionPane.showConfirmDialog(null, "¡Se ha registrado con éxito!", "Deliverya App", dialogo, aux, new ImageIcon("src/main/java/imagen/pulgar-arriba.png"));
			if (resultado == 0) {
				new IniciarSesionCliente().setVisible(true);
				super.dispose();
			}
		}
		
		
	}//GEN-LAST:event_btnRegistrarClienteActionPerformed
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegistroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RegistroCliente().setVisible(true);
			}
		});
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAtras;
	private javax.swing.JButton btnRegistrarCliente;
	private javax.swing.JButton btnTerminos;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JSeparator jSeparator3;
	private javax.swing.JSeparator jSeparator4;
	private javax.swing.JSeparator jSeparator5;
	private javax.swing.JLabel lblApellidoCompleto;
	private javax.swing.JLabel lblFechaNacimiento;
	private javax.swing.JLabel lblLogoDecorado;
	private javax.swing.JLabel lblMinimizar;
	private javax.swing.JLabel lblNombreCompleto;
	private javax.swing.JLabel lblRegistroCliente;
	private javax.swing.JLabel lblRegistroContrasenaCliente;
	private javax.swing.JLabel lblRegistroCorreoCliente;
	private javax.swing.JLabel lblSalir;
	private javax.swing.JLabel lblTerminos;
	private javax.swing.JPanel pnlContenedorRegistroCliente;
	private javax.swing.JPanel pnlFondoRegistroCliente;
	private javax.swing.JPanel pnlRegistroCliente;
	private javax.swing.JTextField txtFechaNacimiento;
	private javax.swing.JTextField txtRegistroApellidoCompleto;
	private javax.swing.JPasswordField txtRegistroContrasenaCliente;
	private javax.swing.JTextField txtRegistroCorreoCliente;
	private javax.swing.JTextField txtRegistroNombreCompleto;
	
	// End of variables declaration//GEN-END:variables
	private void initIcons() {
		addIcon(lblRegistroCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/RegistroCliente.png");
		addIcon(btnAtras, "src/main/java/co/unicauca/domicilios/presentation/imagenes/atrasOff.png");
		addIconRollover(btnAtras, "src/main/java/co/unicauca/domicilios/presentation/imagenes/atrasOn.png");
		addIcon(lblNombreCompleto, "src/main/java/co/unicauca/domicilios/presentation/imagenes/usuario.png");
		addIcon(lblApellidoCompleto, "src/main/java/co/unicauca/domicilios/presentation/imagenes/usuario.png");
		addIcon(lblFechaNacimiento, "src/main/java/co/unicauca/domicilios/presentation/imagenes/calendario.png");
		addIcon(lblRegistroCorreoCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/email.png");
		addIcon(lblRegistroContrasenaCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/contrasena.png");
		addIcon(lblLogoDecorado, "src/main/java/co/unicauca/domicilios/presentation/imagenes/logoDecorado.png");
		addIcon(btnRegistrarCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/iniciar-sesionOff.png");
		addIconRollover(btnRegistrarCliente, "src/main/java/co/unicauca/domicilios/presentation/imagenes/iniciar-sesionOn.png");
		addIcon(lblSalir, "src/main/java/co/unicauca/domicilios/presentation/imagenes/cancelar.png");
		addIcon(lblMinimizar, "src/main/java/co/unicauca/domicilios/presentation/imagenes/flecha-hacia-abajo.png");
	}
	
	private void addIcon(JLabel lb, String pathIcon) {
		ImageIcon img = new ImageIcon(pathIcon);
		Icon icono = new ImageIcon(img.getImage().getScaledInstance(
				lb.getWidth(),
				lb.getHeight(),
				Image.SCALE_DEFAULT));
		lb.setIcon(icono);
		this.repaint();
	}
	
	private void addIcon(JButton bt, String pathIcon) {
		ImageIcon img = new ImageIcon(pathIcon);
		Icon icono = new ImageIcon(img.getImage().getScaledInstance(
				bt.getWidth(),
				bt.getHeight(),
				Image.SCALE_DEFAULT));
		bt.setIcon(icono);
		this.repaint();
	}
	
	private void addIconRollover(JButton bt, String pathIcon) {
		ImageIcon img = new ImageIcon(pathIcon);
		Icon icono = new ImageIcon(img.getImage().getScaledInstance(
				bt.getWidth(),
				bt.getHeight(),
				Image.SCALE_DEFAULT));
		bt.setRolloverIcon(icono);
		this.repaint();
	}
}
